# Copyright 2016, 2017 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

dist: xenial

python: "2.7"

env:
  matrix:
    - BOGUS_JOB=true

matrix:

  exclude:
    - env: BOGUS_JOB=true

  include:
    - os: linux
      compiler: gcc
      env: CXXSTD=03,11,14,1z

    - os: linux
      compiler: gcc-4.7
      env: CXXSTD=03,11
      addons:
        apt:
          packages:
            - g++-4.7

    - os: linux
      compiler: gcc-4.8
      env: CXXSTD=03,11
      addons:
        apt:
          packages:
            - g++-4.8

    - os: linux
      compiler: gcc-4.9
      env: CXXSTD=03,11
      addons:
        apt:
          packages:
            - g++-4.9
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      compiler: gcc-5
      env: CXXSTD=03,11,14,1z
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      compiler: gcc-6
      env: CXXSTD=03,11,14,1z
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      compiler: gcc-7
      env: CXXSTD=03,11,14,17
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      compiler: gcc-8
      env: CXXSTD=03,11,14,17,2a
      addons:
        apt:
          packages:
            - g++-8
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      compiler: gcc-9
      env: CXXSTD=03,11,14,17,2a
      addons:
        apt:
          packages:
            - g++-9
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      compiler: clang
      env: CXXSTD=03,11,14,1z

    - os: linux
      dist: trusty
      compiler: clang-3.5
      env: CXXSTD=03,11,14,1z
      addons:
        apt:
          packages:
            - clang-3.5
            - libstdc++-4.9-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.5

    - os: linux
      compiler: clang-3.6
      env: CXXSTD=03,11,14,1z
      addons:
        apt:
          packages:
            - clang-3.6

    - os: linux
      compiler: clang-3.7
      env: CXXSTD=03,11,14,1z
      addons:
        apt:
          packages:
            - clang-3.7

    - os: linux
      compiler: clang-3.8
      env: CXXSTD=03,11,14,1z
      addons:
        apt:
          packages:
            - clang-3.8

    - os: linux
      compiler: clang-3.9
      env: CXXSTD=03,11,14,1z
      addons:
        apt:
          packages:
            - clang-3.9

    - os: linux
      compiler: clang-4.0
      env: CXXSTD=03,11,14,1z
      addons:
        apt:
          packages:
            - clang-4.0

    - os: linux
      compiler: clang-5.0
      env: CXXSTD=03,11,14,1z
      addons:
        apt:
          packages:
            - clang-5.0

    - os: linux
      compiler: clang-6.0
      env: CXXSTD=03,11,14,17
      addons:
        apt:
          packages:
            - clang-6.0

    - os: linux
      dist: bionic
      compiler: clang-7
      env: CXXSTD=03,11,14,17,2a
      addons:
        apt:
          packages:
            - clang-7

    - os: linux
      compiler: clang-8
      env: CXXSTD=03,11,14,17,2a
      addons:
        apt:
          packages:
            - clang-8

    - os: linux
      dist: bionic
      compiler: clang-9
      env: CXXSTD=03,11,14,17,2a
      addons:
        apt:
          packages:
            - clang-9

    - os: osx
      compiler: clang
      env: CXXSTD=03,11,14,1z

install:
  - BOOST_BRANCH=develop && [ "$TRAVIS_BRANCH" == "master" ] && BOOST_BRANCH=master || true
  - cd ..
  - git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init libs/config
  - git submodule update --init tools/boostdep
  - cp -r $TRAVIS_BUILD_DIR/* libs/typeof
  - python tools/boostdep/depinst/depinst.py typeof
  - ./bootstrap.sh
  - ./b2 headers

script:
  - ./b2 libs/typeof/test toolset=$TRAVIS_COMPILER cxxstd=$CXXSTD

notifications:
  email:
    on_success: always
